name: publish release
on:
  workflow_dispatch: null
  push:
    tags:
    - v*
    - test-release-*

permissions:
  contents: write

jobs:
  create-release:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - name: gh release create
        run: gh release create --repo ${{ github.repository }} "${GITHUB_REF#refs/tags/}"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  macos:
    needs: create-release
    runs-on: macos-13
    timeout-minutes: 30
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@stable
        with:
          targets: aarch64-apple-darwin,x86_64-apple-darwin
      - run: cargo test
      - run: cargo clippy
      - run: cargo build --release --target aarch64-apple-darwin
      - run: cargo build --release --target x86_64-apple-darwin
      - run: lipo -create -output dotslash target/aarch64-apple-darwin/release/dotslash target/x86_64-apple-darwin/release/dotslash
      - run: tar -cv dotslash | gzip --best > "dotslash-darwin.tar.gz"
      - run: tar -cv -C target/x86_64-apple-darwin/release dotslash | gzip --best > "dotslash-darwin-x86_64.tar.gz"
      - run: tar -cv -C target/aarch64-apple-darwin/release dotslash | gzip --best > "dotslash-darwin-aarch64.tar.gz"
      - name: upload release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        shell: bash
        run: |
          gh release upload "${GITHUB_REF#refs/tags/}" "dotslash-darwin.tar.gz"
          gh release upload "${GITHUB_REF#refs/tags/}" "dotslash-darwin-x86_64.tar.gz"
          gh release upload "${GITHUB_REF#refs/tags/}" "dotslash-darwin-aarch64.tar.gz"

  ubuntu-22_04-x86_64:
    needs: create-release
    runs-on: ubuntu-22.04
    timeout-minutes: 30
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@stable
      - run: cargo test
      - run: cargo clippy
      - run: cargo build --release
      - run: tar -cv -C target/release dotslash | gzip --best > "dotslash-linux-x86_64.tar.gz"
      - name: upload release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        shell: bash
        run: gh release upload "${GITHUB_REF#refs/tags/}" "dotslash-linux-x86_64.tar.gz"

  ubuntu-22_04-aarch64:
    needs: create-release
    runs-on: ubuntu-22.04
    timeout-minutes: 30
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@stable
        with:
          targets: aarch64-unknown-linux-gnu
      - name: Install aarch64 build tools
        run: |
          sudo apt update
          sudo apt install -y gcc-aarch64-linux-gnu
      - run: cargo build --target aarch64-unknown-linux-gnu --release
        env:
          CARGO_TARGET_AARCH64_UNKNOWN_LINUX_GNU_LINKER: aarch64-linux-gnu-gcc
      - run: tar -cv -C target/aarch64-unknown-linux-gnu/release dotslash | gzip --best > "dotslash-linux-aarch64.tar.gz"
      - name: upload release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        shell: bash
        run: gh release upload "${GITHUB_REF#refs/tags/}" "dotslash-linux-aarch64.tar.gz"

  windows:
    needs: create-release
    runs-on: windows-latest
    timeout-minutes: 30
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@stable
      - run: cargo test
      - run: cargo clippy
      - run: cargo build --release
      - run: tar czvf dotslash-windows-x86_64.tar.gz -C target/release dotslash.exe
        shell: cmd
      - name: upload release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: gh release upload %GITHUB_REF:~10% dotslash-windows-x86_64.tar.gz
        shell: cmd
